### ISSUE TITLE
[ASK] How to Full Reload if Certain File Modified?

### ISSUE THREAD

**Issue by mzaini30** [reepolee/svelte-routify-windi-vite#10]
Hi. I have a problem with my laptop. If I create new file in `src/pages`, my laptop become hang (CPU 100%). So, I think, the sollution is if `.routify/urlindex.json` modified, Vite `full reload`. But, what is code of this?

Thanks~

**Comment by alesvaupotic** [comment]
I don't think this is an issue with this template. Please, check your development environment in relation to each package involved. Closing for no being able to reproduce.
