### ISSUE TITLE
How to use variants inside @apply in svelte component styles?

### ISSUE THREAD

**Issue by www-chique** [reepolee/svelte-routify-windi-vite#14]
Hey! Great starter template.
However, when I am trying to use the variants inside @apply of the svelte components, I get this error:
![image](https://user-images.githubusercontent.com/29447216/112479610-38f59d00-8d9b-11eb-869e-3972e9a46563.png)

I know it is probably not related to this repo at all, but you are awesome and might have some knowledge on how to tackle this problem.

**Comment by alesvaupotic** [comment]
Hey,

to simplfy, the following will not work: 
```css
button:not(:disabled) {
  @apply bg-blue-100 hover:text-red-700;
}
```

Just move the `:hover` up a level and style it with a separate definition:
```css
button:not(:disabled) {
  @apply bg-blue-100 text-yellow-500;
}

button:not(:disabled):hover {
  @apply text-red-700;
}
```

Would that work for you?

**Comment by www-chique** [comment]
Yes, that's a work-around and it works. But as you can see it almost then resembles vanilla CSS and loses the power of those variants all written in the same line, compact.
However, there is [a fix here](https://github.com/windicss/vite-plugin-windicss/issues/98#issuecomment-804222608), which works.

The only thing I cannot make it work is using a "global" style along with postcss. But that's out of scope from this project.
Many thanks for your reply.
I hope in the future this is rock-solid and can replace the slow other bundlers and becomes the default starter template for Routify. I'll be so happy to jump in once I can iron out the issues I am facing.

**Comment by alesvaupotic** [comment]
Yeah, I used svelte preprocess before, but just adding it kinda defeats the purpose here to run your CSS transformations twice. Sure, replace the native processor with specific if it works for you. I had no need for it.
