### ISSUE TITLE
Windi CSS Compilation Cornercases 

### ISSUE THREAD

**Issue by Taha-Firoz** [reepolee/svelte-routify-windi-vite#5]
I'm using this template to make an internal tool and ran into a couple of issues, nothing that you can't circumvent with a little cheating but they do ruin the experience a bit. They are all related to Windi or how the svelte file is parsed for Windi, I'm not sure if this is the right place for it though but I wanted these problems outlined for other who might face these issues.

#### 1. Conditionally applied classes within class aren't detected by windi
`<span class="{foo?"bg-blue-500":"bg-red-600"}"></span>`
Here Windi will not consider `bg-blue-500` or `bg-red-600` in it's compiled css, whether this is  the  best or worst way to implement such a  feature is  a debate for another day but the easiest fix I have is to make a hidden component and shove these classes in it.

#### 2. `@apply hover:bg-red-300` in a svelte files style tag fails to compile
There's a compilation  error when there's a `:` in an `@apply` statement. I moved the definition to the `style.css` file and everything compiled and worked as normal.

**Comment by alesvaupotic** [comment]
Thanks for pointing that out for future reference. I do not maintain neither WindiCSS nor vite-plugin-windicss. This is a starter template and a work in progress as it depends on early versions of different plugins for vite and windicss.

**Comment by Taha-Firoz** [comment]
Yup, I am aware that this is just a starter template but I wanted people using it to have some closure. I opened an [issue](https://github.com/windicss/vite-plugin-windicss/issues/78) on vite-plugin-windicss
