### ISSUE TITLE
[feature] SSG export

### ISSUE THREAD

**Issue by ImmanuelSamuel** [reepolee/svelte-routify-windi-vite#6]
Could you add SSG export for routify? I tried it but have issues with the modules not loading correctly (searches for modules in node_modules instead of dist/assets).

**Comment by alesvaupotic** [comment]
I'll ask @jakobrosenberg for some help on this one, Routify is his project and using https://github.com/roxiness/spank for SSG. Do mind this is an experimental project on integrating bleeding edge ViteJS and WindiCSS.

**Comment by jakobrosenberg** [comment]
What does Vite's build output structure look like?

**Comment by alesvaupotic** [comment]
![image](https://user-images.githubusercontent.com/1660347/110444556-78df3380-80bd-11eb-802f-cd85f6bd8e20.png)

**Comment by jakobrosenberg** [comment]
Thanks. Seeing as the script has a hash, the `spank` config has to be a separate .js file.

This might work:
```javascript
// spank.config.js
module.exports = {
  entrypoint: "index.html",
  outputDir: "dist",
  inlineDynamicImports: true,
  script: require('fs')
    .readFileSync('./index.html', 'utf8')
    .match(/<script .+?src="\/([^"]+)"/)[1]
}
```

**Comment by ImmanuelSamuel** [comment]
yeah I had made those changes but the other imports do not work i.e., it looks for _layout.js in node_modules folder. @alesvaupotic  do you have the same issue as well or is it only on my end.

**Comment by alesvaupotic** [comment]
Same issue, yes. Stand by for updates.

**Comment by jakobrosenberg** [comment]
https://github.com/roxiness/spank/releases/tag/v1.6.0

No `spank.config.js` required.

`vite.config.js` needs to be updated:
```javascript
  build: {
    polyfillDynamicImport: false,
    cssCodeSplit: false,
    ...
  },
  resolve: {
    dedupe: ['@roxi/routify'],
    ...
```

Fingers crossed. 🤞
