### ISSUE TITLE
ASK - How to use the build output in SSR? Example with ToSSR.

### ISSUE THREAD

**Issue by lamualfa** [reepolee/svelte-routify-windi-vite#7]
The build output from this template is little bit difference compare to the official [starter template](https://github.com/roxiness/routify-starter/). Because of this, I am a little confused about how to integrate using [tossr](https://github.com/roxiness/tossr) for SSR purposes. Are there any instructions so i can do this purposes?

### SRC directory

![image](https://user-images.githubusercontent.com/39755201/110590029-d05acd80-81a9-11eb-8f84-a128d735c718.png)

### Output Directory

![image](https://user-images.githubusercontent.com/39755201/110590090-e7012480-81a9-11eb-9272-67a34874ea03.png)

#### `dist/index.html` (formatted)

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Routify Windi Vite</title>
  <link rel="icon" type="image/png" href="/assets/favicon.png">

  <!-- Is this a replacement for the `app.js` file needed by tossr?  -->
  <script type="module" crossorigin src="/assets/index.343938c9.js"></script>

  <!-- or this?  -->
  <link rel="modulepreload" href="/assets/vendor.988e13b5.js">
  <link rel="stylesheet" href="/assets/index.2b71573f.css">
</head>

<body>
  <div id="app"></div>
</body>

</html>
```

## ToSSR usage

```js
const { tossr } = require('tossr')

const template = 'dist/index.html'
const script = 'dist/app.js'
const url = '/blog/ssr-is-fun'

const html = await tossr(template, script, url)
```

In this case, is the `app.js` script still needed?

## CC:

- @alesvaupotic
- @jakobrosenberg

## Reference

- https://www.freecodecamp.org/news/web-scraping-for-web-developers-a-concise-summary-3af3d0ca4069/
- https://developers.google.com/web/tools/puppeteer/articles/ssr

**Comment by alesvaupotic** [comment]
No instructions for now, sorry. We're aware of the differences and are currently exploring our options. Will notify everyone on development here and at Discord.

**Comment by alesvaupotic** [comment]
Check the latest version and try exporting with `npx spank`
